In [148]:
#Kelompok 15:
#Jyestaputri Laksita
#Nur Adzlina

In [149]:
import pandas as pd
import re

df = pd.read_csv('reelscomment_preprocessed_fix.csv')

print("Ukuran dataset:", df.shape)
print("Nama kolom:", df.columns.tolist())
print("\nContoh komentar:")
display(df[['9_stemming']].head())

Ukuran dataset: (118, 3)
Nama kolom: ['authorId', 'text', '9_stemming']

Contoh komentar:

                                          9_stemming
0                    tidakada tanggungjawab karhutla
1                     hancur hati lihat hutan gundul
2                       cocok tanam sawit kata bakar
3                         tuhan beri ajaib indonesia
4  jangan singkat karhutla sebut hutan lahan gent...

In [150]:
df_pre = df['9_stemming'].dropna()

print("Jumlah dokumen:", len(df_pre))
print("\nContoh teks hasil preprocessing:")
display(df_pre.head())

Jumlah dokumen: 118

Contoh teks hasil preprocessing:

0                      tidakada tanggungjawab karhutla
1                       hancur hati lihat hutan gundul
2                         cocok tanam sawit kata bakar
3                           tuhan beri ajaib indonesia
4    jangan singkat karhutla sebut hutan lahan gent...
Name: 9_stemming, dtype: object

One-Hot Encoding

In [151]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_binary = CountVectorizer(binary=True)
X_binary = vectorizer_binary.fit_transform(df_pre)

df_binary = pd.DataFrame(
    X_binary.toarray(),
    columns=vectorizer_binary.get_feature_names_out()
)

print("Ukuran matriks:", df_binary.shape)
display(df_binary.head(10))

Ukuran matriks: (118, 366)

,aceh,air,ajaib,akhirat,aktif,alam,alami,alat,allah,aman,...,usaha,utama,versi,wajib,waktu,wapres,warga,waris,yaallah,yaampun
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [152]:
vectorizer_count = CountVectorizer()
X_count = vectorizer_count.fit_transform(df_pre)

df_count = pd.DataFrame(
    X_count.toarray(),
    columns=vectorizer_count.get_feature_names_out()
)

print("Ukuran matriks:", df_count.shape)
display(df_count.head())

Ukuran matriks: (118, 366)

,aceh,air,ajaib,akhirat,aktif,alam,alami,alat,allah,aman,...,usaha,utama,versi,wajib,waktu,wapres,warga,waris,yaallah,yaampun
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

TF-IDF

In [153]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(df_pre)

df_tfidf = pd.DataFrame(
    X_tfidf.toarray(),
    columns=vectorizer_tfidf.get_feature_names_out()
)

print("Ukuran matriks:", df_tfidf.shape)
display(df_tfidf.head())

Ukuran matriks: (118, 366)

,aceh,air,ajaib,akhirat,aktif,alam,alami,alat,allah,aman,...,usaha,utama,versi,wajib,waktu,wapres,warga,waris,yaallah,yaampun
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.602944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [154]:
#Tokenize untuk Word2Vec dan FastText

import nltk
from nltk import word_tokenize
from tqdm.auto import tqdm

nltk.download('punkt')
nltk.download('punkt_tab')

sentences = [
    word_tokenize(comment.lower())
    for comment in tqdm(df_pre, desc="Tokenisasi")
]

print("Contoh token:")
print(sentences[:5])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Tokenisasi:   0%|          | 0/118 [00:00<?, ?it/s]

Contoh token:
[['tidakada', 'tanggungjawab', 'karhutla'], ['hancur', 'hati', 'lihat', 'hutan', 'gundul'], ['cocok', 'tanam', 'sawit', 'kata', 'bakar'], ['tuhan', 'beri', 'ajaib', 'indonesia'], ['jangan', 'singkat', 'karhutla', 'sebut', 'hutan', 'lahan', 'genting', 'lebih', 'rasa']]

Word2Vec

In [155]:
!pip install -q gensim

In [156]:
import gensim.models

# 1. Train model
model = gensim.models.Word2Vec(
    sentences,
    min_count=1,
    vector_size=100,
    window=5,
    sg=0,
    seed=42,
    workers=1
)

# 2. Save model
model.save('sentimen_reels.w2v')

# 3. Load model
model = gensim.models.Word2Vec.load('sentimen_reels.w2v')

# 4. Model information
w2v = model.wv

print("10 kata pertama:", w2v.index_to_key[:10])
print("Ukuran matriks dan vektor:", w2v.vectors.shape)
print("Dimensi vektor:", w2v.vector_size)

10 kata pertama: ['sawit', 'kalimantan', 'tidak', 'bakar', 'hutan', 'yaallah', 'moga', 'asap', 'parah', 'lahan']
Ukuran matriks dan vektor: (366, 100)
Dimensi vektor: 100

In [157]:
kata = 'pakai'

if kata in w2v:
    print(w2v.similar_by_key(kata, topn=5))
else:
    print(f"Kata '{kata}' tidak ditemukan dalam kosakata.")

    if len(w2v.index_to_key) > 0:
        kata = w2v.index_to_key[0]
        print("Contoh kata alternatif:", kata)
        print(w2v.similar_by_key(kata, topn=5))

Kata 'pakai' tidak ditemukan dalam kosakata.
Contoh kata alternatif: sawit
[('sembuh', 0.2797190546989441), ('ulas', 0.2724459767341614), ('sudah', 0.23952972888946533), ('keluarga', 0.23376686871051788), ('bodoh', 0.22828973829746246)]

In [158]:
import numpy as np

def get_document_vector(tokens, model):
    valid_vectors = [
        model.wv[word]
        for word in tokens
        if word in model.wv
    ]

    if not valid_vectors:
        return np.zeros(model.vector_size)

    return np.mean(valid_vectors, axis=0)

X_features_w2v = np.array([
    get_document_vector(doc, model)
    for doc in sentences
])

df_w2v = pd.DataFrame(X_features_w2v)

print("Ukuran matriks fitur dokumen:", df_w2v.shape)
display(df_w2v.head())

Ukuran matriks fitur dokumen: (118, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.004733,0.002585,0.000946,-0.004931,-0.000910,0.001978,0.001292,-0.002105,-0.005117,0.001381,...,-0.002321,-0.001548,0.001376,-0.005255,-0.004132,0.002221,-0.003347,0.004925,-0.005858,0.004953
1,0.000403,-0.003070,-0.001503,0.003385,0.001022,0.002119,0.001921,-0.002168,0.001620,-0.003801,...,-0.001357,0.003686,0.001007,-0.004587,0.002821,-0.004283,-0.002252,0.002889,0.001899,-0.004572
2,-0.000142,0.005282,-0.000460,0.003987,0.000236,0.001691,0.000883,-0.000460,-0.001090,-0.004998,...,0.000449,0.000112,0.001391,-0.000326,0.000278,-0.002431,-0.000730,0.003173,-0.003663,-0.003105
3,0.007825,0.000616,0.002287,-0.001547,0.005142,-0.005794,0.002284,-0.004708,0.003285,0.001087,...,-0.001602,-0.002200,-0.000102,-0.006571,0.000953,0.001968,0.001851,0.004398,0.002143,-0.006078
4,0.000323,0.000967,0.002327,0.000716,0.000126,0.002335,0.001928,-0.002452,-0.000723,-0.002425,...,0.000611,-0.000725,-0.001190,-0.000584,0.000190,0.000512,-0.002984,0.001965,0.000185,0.000368

Visualisasi Word2Vec

In [159]:
!pip install -q umap-learn plotly

In [160]:
from umap import UMAP
import plotly.express as px

if len(w2v.index_to_key) >= 3:
    reducer = UMAP(
        n_components=2,
        random_state=42,
        n_neighbors=min(30, len(w2v.index_to_key) - 1)
    )

    X_umap_w2v = reducer.fit_transform(w2v.vectors)

    df_umap_w2v = pd.DataFrame(
        X_umap_w2v,
        columns=['umap1', 'umap2']
    )

    df_umap_w2v['word'] = w2v.index_to_key

    fig = px.scatter(
        df_umap_w2v,
        x='umap1',
        y='umap2',
        text='word',
        title='Word2Vec Visualization'
    )

    fig.update_traces(textposition='top center')
    fig.update_layout(height=800)
    fig.show()
else:
    print("Kosakata terlalu sedikit untuk visualisasi UMAP.")

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

FastText

In [161]:
import gensim.models

# 1. Build model
model_fasttext = gensim.models.FastText(
    sentences,
    min_count=2,
    vector_size=100,
    window=5,
    min_n=3,
    max_n=6,
    sg=1,
    epochs=10,
    seed=42,
    workers=1
)

# 2. Save model
model_fasttext.save('sentimen_reels.fasttext')

# 3. Load model
model_fasttext = gensim.models.FastText.load(
    'sentimen_reels.fasttext'
)

# 4. Model information
fastext = model_fasttext.wv

print("10 kata pertama:", fastext.index_to_key[:10])
print("Ukuran matriks vektor:", fastext.vectors.shape)
print("Dimensi vektor:", fastext.vector_size)

10 kata pertama: ['sawit', 'kalimantan', 'tidak', 'bakar', 'hutan', 'yaallah', 'moga', 'asap', 'parah', 'lahan']
Ukuran matriks vektor: (134, 100)
Dimensi vektor: 100

In [162]:
kata = '4g'

if kata in fastext:
    print(fastext.similar_by_key(kata, topn=5))
else:
    print(f"Kata '{kata}' tidak ditemukan dalam kosakata.")

    if len(fastext.index_to_key) > 0:
        kata = fastext.index_to_key[0]
        print("Contoh kata alternatif:", kata)
        print(fastext.similar_by_key(kata, topn=5))

[('gesek', 0.23163944482803345), ('pedih', 0.21673904359340668), ('masuk', 0.2099463790655136), ('manusia', 0.20694264769554138), ('muncul', 0.19251562654972076)]

In [163]:
def get_document_vector_fasttext(tokens, model):
    valid_vectors = [
        model.wv[word]
        for word in tokens
        if word in model.wv
    ]

    if not valid_vectors:
        return np.zeros(model.vector_size)

    return np.mean(valid_vectors, axis=0)

X_features_fasttext = np.array([
    get_document_vector_fasttext(doc, model_fasttext)
    for doc in sentences
])

df_fasttext = pd.DataFrame(X_features_fasttext)

print("Ukuran matriks fitur dokumen:", df_fasttext.shape)
display(df_fasttext.head())

Ukuran matriks fitur dokumen: (118, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.000520,0.000560,0.000451,-0.001065,-0.000225,0.001457,0.001894,0.000004,-0.000884,-0.000215,...,-0.000666,-0.001876,0.000898,0.001467,-0.000221,0.000476,0.000199,0.000430,-0.001555,0.001855
1,0.000950,0.001759,-0.000219,0.000540,0.000798,0.000346,0.001403,-0.000275,-0.000903,-0.001856,...,0.000505,-0.002435,0.000648,0.000037,-0.001099,-0.001735,-0.000541,0.001699,0.000341,-0.000387
2,0.001523,0.000308,0.000185,-0.000130,-0.000231,0.002484,0.001816,0.000322,-0.001197,-0.000747,...,0.001265,-0.002920,0.001138,0.000675,-0.001195,-0.000058,-0.000797,-0.001399,-0.000349,0.000770
3,0.000210,0.001060,0.001548,0.000685,-0.000274,0.001253,0.000742,-0.000999,0.000316,0.000996,...,0.000041,-0.002009,0.000133,0.000056,-0.000730,-0.000396,-0.000524,-0.000506,0.000173,-0.000073
4,0.000764,0.001301,0.000123,0.000025,0.001025,0.001881,0.001820,-0.000461,-0.001584,-0.000522,...,-0.000208,-0.002716,0.000378,0.000934,-0.000586,-0.000364,-0.000094,0.001108,0.000567,0.000663

Visualisasi FastText

In [164]:
if len(fastext.index_to_key) >= 3:
    reducer_fasttext = UMAP(
        n_components=2,
        random_state=42,
        min_dist=0.3,
        n_neighbors=min(25, len(fastext.index_to_key) - 1)
    )

    X_umap_fasttext = reducer_fasttext.fit_transform(
        fastext.vectors
    )

    df_umap_fasttext = pd.DataFrame(
        X_umap_fasttext,
        columns=['umap1', 'umap2']
    )

    df_umap_fasttext['word'] = fastext.index_to_key

    fig = px.scatter(
        df_umap_fasttext,
        x='umap1',
        y='umap2',
        text='word',
        title='FastText Visualization'
    )

    fig.update_traces(textposition='top center')
    fig.update_layout(height=800)
    fig.show()
else:
    print("Kosakata terlalu sedikit untuk visualisasi UMAP.")

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.